### ISSUE TITLE
Add .idea/ to .gitignore

### ISSUE THREAD

**Issue by fredkneeland** [fredkneeland/DNA_Analysis#2]
In the last pr, I relealized that the .idea/ folder was committed, this should not be the case

**Comment by JoeBanks13** [comment]
I'll take it

**Comment by JoeBanks13** [comment]
Done :ok_hand:

**Comment by fredkneeland** [comment]
pr: https://github.com/fredkneeland/DNA_Analysis/pull/12#pullrequestreview-67846427
